<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- SPDX-FileCopyrightText: 2023-Present The Lula Authors -->

<script lang="ts">
	import type { Control, Mapping } from '$lib/types';
	import { wsClient } from '$lib/websocket';
	import { MappingCard, MappingForm } from '..';
	import { EmptyState } from '../../ui';

	interface Props {
		control: Control;
		mappings: Mapping[];
	}

	let { control, mappings }: Props = $props();

	// Component state
	let showNewMappingForm = $state(false);
	let editingMapping = $state<Mapping | null>(null);

	// Form state
	let newMappingData = $state({
		justification: '',
		status: 'planned' as 'planned' | 'implemented' | 'verified'
	});

	// Event handlers
	async function handleCreateMapping(data: typeof newMappingData) {
		try {
			const mappingData = {
				control_id: control.id,
				justification: data.justification,
				status: data.status,
				source_entries: [],
				uuid: '' // Will be generated by backend
			};

			await wsClient.createMapping(mappingData);
			resetMappingForm();
		} catch (error) {
			console.error('Failed to create mapping:', error);
		}
	}

	function cancelNewMapping() {
		resetMappingForm();
	}

	function resetMappingForm() {
		newMappingData = {
			justification: '',
			status: 'planned'
		};
		showNewMappingForm = false;
		editingMapping = null;
	}

	function startEditMapping(mapping: Mapping) {
		editingMapping = { ...mapping };
		showNewMappingForm = true;
		newMappingData = {
			justification: mapping.justification,
			status: mapping.status
		};
	}

	async function handleUpdateMapping(data: typeof newMappingData) {
		if (!editingMapping) return;

		try {
			const updatedMapping = {
				...editingMapping,
				justification: data.justification,
				status: data.status
			};

			await wsClient.updateMapping(updatedMapping);
			resetMappingForm();
		} catch (error) {
			console.error('Failed to update mapping:', error);
		}
	}

	async function handleDeleteMapping(uuid: string) {
		try {
			await wsClient.deleteMapping(uuid);
		} catch (error) {
			console.error('Failed to delete mapping:', error);
		}
	}
</script>

<div class="space-y-6">
	<!-- Add New Mapping Section -->
	<div class="mb-6">
		{#if !showNewMappingForm}
			<button
				onclick={() => (showNewMappingForm = true)}
				class="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
			>
				<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M12 6v6m0 0v6m0-6h6m-6 0H6"
					/>
				</svg>
				Add New Mapping
			</button>
		{:else}
			<div
				class="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 shadow-sm"
			>
				<MappingForm
					initialData={newMappingData}
					onSubmit={editingMapping ? handleUpdateMapping : handleCreateMapping}
					onCancel={cancelNewMapping}
					submitLabel={editingMapping ? 'Update Mapping' : 'Create Mapping'}
				/>
			</div>
		{/if}
	</div>

	<!-- Existing Mappings -->
	{#if mappings.length > 0}
		<div class="mb-4">
			<div class="space-y-4">
				{#each mappings as mapping}
					<MappingCard
						{mapping}
						showActions={true}
						onEdit={startEditMapping}
						onDelete={handleDeleteMapping}
					/>
				{/each}
			</div>
		</div>
	{:else}
		<EmptyState
			title="No mappings yet"
			description="Create your first mapping for this control."
		/>
	{/if}
</div>