ignore:
  - node_modules
  - dist
  - coverage
  - integration/test-files/**
  - src/lib/components/ui/index.ts
  - src/lib/components/version-control/index.ts
  - src/lib/components/setup/index.ts
  - src/lib/components/controls/tabs/index.ts
  - src/lib/components/controls/renderers/index.ts
  - src/lib/components/controls/index.ts
  - src/lib/components/control-sets/index.ts
  - src/lib/types.ts
  - src/lib/index.ts
  - cli/server/types.ts
  - src/app.d.ts
  - src/lib/form-types.ts
