Output images/component-defn-console-validation-detail.gif

Require lula
Set FontSize 14
Set Width 1850
Set Height 925
Set Framerate 24
Set Padding 5

Hide
Type "lula console -f ./src/test/unit/common/oscal/valid-multi-component-validations.yaml" Enter
Sleep 1s
Show

# Navigate to a control and select
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Enter
Sleep 1s
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Type "d"
Sleep 1s
Down
Sleep 500ms
Down
Sleep 1s
Up
Sleep 500ms
Up
Sleep 1s
