name: PR Title Check

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
  merge_group:

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  title_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22.20.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Ensure pnpm store exists
        run: pnpm store path | xargs -I{} mkdir -p "{}"

      - name: Install commitlint
        run: npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Lint PR title
        if: ${{ github.event.pull_request && github.event.pull_request.title }}
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
