name: Node Tests

on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    paths-ignore:
    - "LICENSE"
    - "CODEOWNERS"

permissions:
  id-token: write # This is needed for OIDC federation.
  contents: read
  issues: write # Needed for integration tests to comment on PRs
  pull-requests: write # Needed for integration tests to comment on PRs

jobs:
  on-demand-workflows:
    uses: ./.github/workflows/on-demand-workflows.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      run-format: true
      run-units: true
      run-integration: true

